modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPL 3.0"
[[mods]]
modId="mycustomtweaks"
version="${file.jarVersion}"
displayName="MyCustomTweaks"
displayURL="https://github.com/LeoBeliik/MyCustomTweaks"
authors="LeoBeliik"
description='''
Some tweaks
'''
[[dependencies.mycustomtweaks]]
   modId="forge"
   mandatory=true
   versionRange="[40,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.mycustomtweaks]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,)"
   ordering="NONE"
   side="BOTH"
